version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: mmnt-challenge-db
    environment:
      - POSTGRES_DB=mmnt_challenge_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
        - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: mmnt-challenge-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    networks:
      - app-network

  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    image: nodejs
    container_name: mmnt-challenge-backend
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=$PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - JWT_SECRET=$JWT_SECRET
      - DATABASE_URL=$DATABASE_URL
    ports:
      - "8080:3000"
    volumes:
      - ../backend/:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    depends_on:
      - postgres

  frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    image: react
    container_name: mmnt-challenge-frontend
    ports:
      - "80:80"
    volumes:
      - ../frontend/:/app
      - node_modules_front:/app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
  node_modules_front:

